name: Build Game

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install pygame pypresence Pillow numpy opencv-python pyglet requests astral pytz googletrans==4.0.0rc1 pymunk aiohttp websockets
        pip install pyinstaller

    # ---------------- WINDOWS ----------------
    - name: Build Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        pyinstaller --noconfirm ^
        --add-data "cutscenes;cutscenes" ^
        --add-data "music;music" ^
        --add-data "sprites;sprites" ^
        --add-data "worlds;worlds" ^
        --add-data "icon;icon" ^
        --add-data "ui;ui" ^
        --add-data "interactables;interactables" ^
        --add-data "multiplayer;multiplayer" ^
        --collect-submodules sprites.physic_obj ^
        --clean ^
        --name windows ^
        main.py

    # ---------------- LINUX ----------------
    - name: Build Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        pyinstaller --noconfirm \
        --add-data "cutscenes:cutscenes" \
        --add-data "music:music" \
        --add-data "sprites:sprites" \
        --add-data "worlds:worlds" \
        --add-data "icon:icon" \
        --add-data "ui:ui" \
        --add-data "interactables:interactables" \
        --add-data "multiplayer:multiplayer" \
        --collect-submodules sprites.physic_obj \
        --clean \
        --name linux \
        main.py

    # ---------------- UPLOAD ----------------
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ runner.os }}
        path: dist/*