name: Build & Upload Game

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install deps
      run: |
        pip install pygame pypresence Pillow numpy opencv-python pyglet aiohttp websockets
        pip install pyinstaller

    # ---------------- WINDOWS BUILD ----------------
    - name: Build Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        pyinstaller --noconfirm ^
        --add-data "cutscenes;cutscenes" ^
        --add-data "music;music" ^
        --add-data "sprites;sprites" ^
        --add-data "worlds;worlds" ^
        --add-data "icon;icon" ^
        --add-data "ui;ui" ^
        --add-data "interactables;interactables" ^
        --add-data "multiplayer;multiplayer" ^
        --collect-submodules sprites.physic_obj ^
        --clean ^
        --name windows ^
        main.py

    # ---------------- LINUX BUILD ----------------
    - name: Build Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        pyinstaller --noconfirm \
        --add-data "cutscenes:cutscenes" \
        --add-data "music:music" \
        --add-data "sprites:sprites" \
        --add-data "worlds:worlds" \
        --add-data "icon:icon" \
        --add-data "ui:ui" \
        --add-data "interactables:interactables" \
        --add-data "multiplayer:multiplayer" \
        --collect-submodules sprites.physic_obj \
        --clean \
        --name linux \
        main.py

    # ---------------- DOWNLOAD BUTLER ----------------
    - name: Download Butler
      if: runner.os == 'Windows'
      run: |
        curl -L -o butler.zip https://itch.io/butler/windows-amd64/LATEST/archive/default
        powershell Expand-Archive butler.zip -DestinationPath butler

    # ---------------- UPLOAD TO ITCH ----------------
    - name: Upload to itch (Windows)
      if: runner.os == 'Windows'
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: |
        butler\butler.exe push dist YOURNAME/YOURGAME:windows --userversion "${{ github.run_number }}"