name: Daily Auto Release

on:
  schedule:
    - cron: "* * * * *"   # every minute
  workflow_dispatch:       # manual trigger button

permissions:
  contents: write   #

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get today's date (Amsterdam time)
        id: date
        run: |
          echo "DATE=$(TZ=Europe/Amsterdam date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Check if release already exists
        id: check
        run: |
          TAG="${{ steps.date.outputs.DATE }}"

          if git ls-remote --tags origin | grep -q "refs/tags/$TAG"; then
            echo "ALREADY=true" >> $GITHUB_OUTPUT
          else
            echo "ALREADY=false" >> $GITHUB_OUTPUT
          fi

      - name: Create zip archive
        if: steps.check.outputs.ALREADY == 'false'
        run: zip -r source.zip . -x "*.git*"

      - name: Create GitHub Release
        if: steps.check.outputs.ALREADY == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.DATE }}
          name: Release ${{ steps.date.outputs.DATE }}
          files: source.zip
          token: ${{ github.token }}