name: Nightly NL Release

on:
  schedule:
    - cron: "0 * * * *"  # elk uur
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check NL time (only 02:00)
        id: timecheck
        run: |
          export TZ="Europe/Amsterdam"
          HOUR=$(date +%H)

          echo "Current NL hour: $HOUR"

          if [ "$HOUR" != "02" ]; then
            echo "Not release time. EXITING."
            exit 0
          fi

          echo "OK_RELEASE=true" >> $GITHUB_OUTPUT

      - name: Set date
        if: steps.timecheck.outputs.OK_RELEASE == 'true'
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create zip
        if: steps.timecheck.outputs.OK_RELEASE == 'true'
        run: zip -r source.zip . -x "*.git*"

      - name: Create Release
        if: steps.timecheck.outputs.OK_RELEASE == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.DATE }}
          name: Release ${{ steps.date.outputs.DATE }}
          files: source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}